/* Copyright (c) 2022 bitlap.org */
package org.bitlap.jdbc

import org.bitlap.client.BitlapClient
import org.bitlap.jdbc.BitlapConnection.URI_PREFIX
import org.bitlap.network.handles._
import org.bitlap.tools.apply

import java.sql._
import java.util.Properties
import java.util.concurrent.Executor
import java._
import scala.jdk.CollectionConverters._

/** bitlap Connection
 *
 *  @author
 *    梦境迷离
 *  @since 2021/6/6
 *  @version 1.0
 */
@apply
class BitlapConnection(uri: String, info: Properties) extends Connection {
  // apply not support default args

  private var session: SessionHandle   = _
  private var closed                   = true
  private var warningChain: SQLWarning = _
  private var client: BitlapClient     = _

  {
    if (!uri.startsWith(URI_PREFIX)) {
      throw BitlapSQLException(s"Invalid URL: $uri")
    }
    // remove prefix
    val uriWithoutPrefix = uri.substring(URI_PREFIX.length)
    val hosts            = uriWithoutPrefix.split(",")
    // parse uri
    val serverPeers = hosts.map(f => f.split("/")(0))
    val db          = hosts.filter(_.contains("/")).map(_.split("/")(1)).headOption.getOrElse(Constants.DEFAULT_DB)
    info.put(Constants.DBNAME_PROPERTY_KEY, db)
    try {
      client = new BitlapClient(serverPeers, info.asScala.toMap)
      session = client.openSession()
      closed = false
    } catch {
      case e: Exception =>
        e.printStackTrace()
        throw BitlapSQLException(
          s"Bitlap openSession failed, connect to serverPeers: ${serverPeers.mkString("Array(", ", ", ")")}",
          cause = e
        )
    }
  }

  override def unwrap[T](iface: Class[T]): T = ???

  override def isWrapperFor(iface: Class[_]): Boolean = ???

  override def close(): Unit =
    try
      if (session != null) {
        client.closeSession(session)
      }
    finally closed = true

  override def createStatement(): Statement =
    if (session != null) {
      new BitlapStatement(this, session, client)
    } else {
      throw BitlapSQLException("Can't create Statement, connection is closed");
    }

  override def isClosed(): Boolean = closed

  override def clearWarnings(): Unit = warningChain = null

  override def prepareStatement(sql: String): PreparedStatement = ???

  override def prepareCall(sql: String): CallableStatement = ???

  override def nativeSQL(sql: String): String = ???

  override def setAutoCommit(autoCommit: Boolean): Unit = ???

  override def getAutoCommit: Boolean = ???

  override def commit(): Unit = ()

  override def rollback(): Unit = ()

  override def getMetaData: DatabaseMetaData = {
    if (closed) throw new SQLException("Connection is closed")
    new BitlapDatabaseMetaData(this, session, client)
  }

  override def setReadOnly(readOnly: Boolean): Unit = ???

  override def isReadOnly: Boolean = false

  override def setCatalog(catalog: String): Unit = ???

  override def getCatalog: String = ""

  override def setTransactionIsolation(level: Int): Unit = ???

  override def getTransactionIsolation: Int = ???

  override def getWarnings: SQLWarning = warningChain

  override def createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement = ???

  override def prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement = ???

  override def prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int): CallableStatement = ???

  override def getTypeMap: util.Map[String, Class[_]] = ???

  override def setTypeMap(map: util.Map[String, Class[_]]): Unit = ???

  override def setHoldability(holdability: Int): Unit = ???

  override def getHoldability: Int = ???

  override def setSavepoint(): Savepoint = ???

  override def setSavepoint(name: String): Savepoint = ???

  override def rollback(savepoint: Savepoint): Unit = ???

  override def releaseSavepoint(savepoint: Savepoint): Unit = ???

  override def createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): Statement =
    ???

  override def prepareStatement(
    sql: String,
    resultSetType: Int,
    resultSetConcurrency: Int,
    resultSetHoldability: Int
  ): PreparedStatement = ???

  override def prepareCall(
    sql: String,
    resultSetType: Int,
    resultSetConcurrency: Int,
    resultSetHoldability: Int
  ): CallableStatement = ???

  override def prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement = ???

  override def prepareStatement(sql: String, columnIndexes: scala.Array[Int]): PreparedStatement = ???

  override def prepareStatement(sql: String, columnNames: scala.Array[String]): PreparedStatement = ???

  override def createClob(): Clob = ???

  override def createBlob(): Blob = ???

  override def createNClob(): NClob = ???

  override def createSQLXML(): SQLXML = ???

  override def isValid(timeout: Int): Boolean = {
    if (timeout < 0) throw new SQLException("timeout value was negative")
    if (closed) return false
    var rc = false
    try {
      new BitlapDatabaseMetaData(this, session, client).getDatabaseProductName
      rc = true
    } catch {
      case _: SQLException =>
    }
    rc
  }

  override def setClientInfo(name: String, value: String): Unit = ???

  override def setClientInfo(properties: Properties): Unit = ???

  override def getClientInfo(name: String): String = ???

  override def getClientInfo: Properties = ???

  override def createArrayOf(typeName: String, elements: scala.Array[AnyRef]): sql.Array = ???

  override def createStruct(typeName: String, attributes: scala.Array[AnyRef]): Struct = ???

  override def setSchema(schema: String): Unit = {
    // JDK 1.7
    if (closed) throw new SQLException("Connection is closed")
    if (schema == null || schema.isEmpty) throw new SQLException("Schema name is null or empty")
    if (schema.contains(";")) throw new SQLException("invalid schema name")
    var stmt: Statement = null
    try {
      stmt = createStatement()
      stmt.execute("USE " + schema)
    } finally if (stmt != null) stmt.close()
  }

  override def getSchema: String = {
    if (closed) throw BitlapSQLException("Connection is closed")
    var res: ResultSet  = null
    var stmt: Statement = null
    try {
      stmt = createStatement()
      res = stmt.executeQuery("SHOW CURRENT_DATABASE")
      if (res == null || !res.next) throw BitlapSQLException("Failed to get schema information")
    } finally {
      if (res != null) res.close()
      if (stmt != null) stmt.close()
    }
    res.getString(1)
  }

  override def abort(executor: Executor): Unit = ???

  override def setNetworkTimeout(executor: Executor, milliseconds: Int): Unit = ???

  override def getNetworkTimeout: Int = ???
}
object BitlapConnection {
  private val URI_PREFIX = "jdbc:bitlap://"
}
